### ISSUE TITLE
Move not working

### ISSUE THREAD

**Issue by mkolar** [wiremas/spore#3]
This might very well be related to #1 . All the tools seem to be working despite throwing lots of errors and being somewhat unstable on re-opened scenes (unable to delet objects for example after opening a scene), But the move tool is not working at all for us. Whenever we try it, we get this.

Any idea? We'll try finding what's causing it, but though you should know. 

```
Traceback (most recent call last):
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 1257, in mouse_moved
#     self.help_display.set_visible(True)
#   File "S:\Maya_2018_DI\build\Release\runTime\Python\Lib\site-packages\maya\OpenMayaMPx.py", line 5599, in <lambda>
#   File "S:\Maya_2018_DI\build\Release\runTime\Python\Lib\site-packages\maya\OpenMayaMPx.py", line 80, in _swig_getattr
# AttributeError: 'MPxContext' object has no attribute 'help_display'
# Traceback (most recent call last):
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 1327, in dragged
#     self.tool_cmd.doIt()
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 157, in doIt
#     self.move_action(flag)
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 573, in move_action
#     direction = om.MVector(self.brush_state.stroke_direction[0],
# IndexError: tuple index out of range
# Traceback (most recent call last):
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 1345, in released
#     self.tool_cmd.doIt()
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 157, in doIt
#     self.move_action(flag)
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 573, in move_action
#     direction = om.MVector(self.brush_state.stroke_direction[0],
# IndexError: tuple index out of range
```

**Comment by mkolar** [comment]
this was fixed now. thank you
