### ISSUE TITLE
Remove tool breaking - InstanceData is out of sync

### ISSUE THREAD

**Issue by mkolar** [wiremas/spore#4]
Hey.

In some spores, when we want to use the `remove` button we get the following error:
```
# Traceback (most recent call last):
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 1302, in clicked
#     self.tool_cmd.doIt()
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 182, in doIt
#     self.change_visibility(flag, 0)
#   File "K:/core/software/maya/spore/plug-ins\scripted\spore_context.py", line 676, in change_visibility
#     old_vis = self.instance_data.visibility[index]
#   File "S:\Maya_2018_DI\build\Release\runTime\Python\Lib\site-packages\maya\OpenMaya.py", line 13619, in __getitem__
# IndexError: list index out of range
```

In the same scene when saving the scene this pops up
```
100
100
100
51
100
100
100
100
100
100
100
100
// Error: instance_data : Cleanup operation failed, Instance Data is out of sync. // 
// scripted.spore_context : Spore Context clean up // 
file -save;
// Result: P:/path/to/scene/scene.ma // 
// Error: instance_data : InstanceData validation failed! // 
```

There is 100 instances in this spore so one of those assert (the visibility one) seems to be off, but I can't figure out why.

Here's a link to a cleaned up scene where this is happening. http://bit.ly/spore_remove_bug

Unfortunately it's a little bit random, so we can't get a reproducible from just a few steps. Hope this is enough to find out what's going on.

Thanks

**Comment by mkolar** [comment]
interesting. we'll keep an eye on when exactly this starts happening and try to isolate it better. I think we only experienced it with the visibility so far, so the hotfix will actually help. Having to re-delete some points is better than having to throw away the full node :).
